### ISSUE TITLE
Crash on launch, Server and Client

### ISSUE THREAD

**Issue by yuma-dev** [embeddedt/CreateChunkloading#12] opened 2022-07-25 15:51 UTC
When adding this mod my Server and my Client all crash, tried different mod combinations with no luck
Latest.log : https://gist.github.com/yuma-dev/55a00ba120a802b18a353e81efa0d3c7

**Comment by embeddedt** [comment] 2022-07-25 15:52
Hmm, the crash log does not mention Create Chunkloading as causing the issue, but it does look like this specific crash is caused by Essential. Have you tried running the game with it disabled as a test? If it still crashes, please send the new log.

**Comment by yuma-dev** [comment] 2022-07-25 15:55
With Essential disabled it still crashes

crashlog : https://gist.github.com/yuma-dev/ff7ca23835230c6576174530ff9db981
latest.log : https://gist.github.com/yuma-dev/47f3e8472648ab732f7c16fbb1666b92

**Comment by embeddedt** [comment] 2022-07-25 15:57
Ah, now I see the problem (the latest.log doesn't show the actual crash for some reason?). You need to use the right mod version for your Create version. I don't think Fabric Create has released a 0.5 version yet so you should stick with version 1.1.0 of my mod, as outlined on the [mod page](https://www.curseforge.com/minecraft/mc-mods/create-chunkloading). :slightly_smiling_face:

**Comment by yuma-dev** [comment] 2022-07-25 16:03
Edit because what I wrote was very confusing:
There is no 1.1.0 Version for Fabric on your Modpage

**Comment by yuma-dev** [comment] 2022-07-25 16:04
ignore this comment as I edited the Comment above thinking I could delete this one

**Comment by yuma-dev** [comment] 2022-07-25 16:24
Is that an Issue on my end? Or is there really no 1.1.0 Fabric Version

**Comment by embeddedt** [comment] 2022-07-25 17:17
https://www.curseforge.com/minecraft/mc-mods/create-chunkloading/files/3739771

**Comment by embeddedt** [comment] 2022-08-13 22:13
I'm closing this as I think the inquiry is resolved.

**Closed as completed by embeddedt** 2022-08-13 22:13 UTC
